### ISSUE TITLE
Songs appears in Music but not in Stage Select

### ISSUE THREAD

**Issue by Maxray0** [Deinonychus71/Sm5shMusic#70]
Hi, I have the exact same issue as  https://github.com/Deinonychus71/Sma5hMusic/issues/57 . I already used your script to fix that but in the end, the problem is still here for me.
![IMG_20211020_235833](https://user-images.githubusercontent.com/92893593/138178496-f9af4306-c15b-4766-ae3d-702113753931.jpg)
![IMG_20211020_235931](https://user-images.githubusercontent.com/92893593/138178502-e40fcc7e-aafa-46c3-83f4-f9a44fd4b80d.jpg)
Do you need my mods folder or anything?
Thank you in advance!
Have a great day!

**Comment by Deinonychus71** [comment]
Even if you use the battlefield music select for all the stages your songs still need to be added to playlists otherwise they won't show up.

there is some wip work to automatically songs in playlist to circumvent that issue but since you're using a custom series it doesn't work for that yet, so you need to add your song to a playlist. Most people add them in battlefield playlist
